apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-oa78
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-oa78
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-oa78
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-oa78
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-oa78
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-euzz-tenant/rhtap-demo-app/hacbs-test-project-oa78@sha256:55668263d22735912e5affbb1b428ec746927c6e80f47061d4af512d0f9b8782
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
