apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oa78
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-euzz-tenant/rhtap-demo-app/hacbs-test-project-oa78@sha256:55668263d22735912e5affbb1b428ec746927c6e80f47061d4af512d0f9b8782
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
